server:
  port: 8000
  
spring:
  application:
    name: apigateway-service1
    
  cloud:
    gateway:
      routes:
      - id: member-service
        uri: lb://MEMBER-SERVICE
        predicates:
        - Path=/member-service/** # 유저가 브라우저 주소창에 http://localhost:8000/user-service/users를 입력하면  user-service를 보고 id를 확인하고 uri로 넘어간다.
        - Method=GET, POST, PUT, DELETE # 해당 코드를 아예 적지 않으면 모두 허용이다.  
  
      - id: board-service # 순서 2번
        uri: lb://BOARD-SERVICE # 순서 3번
        predicates:
        - Path=/board-service/** # 순서 1번 / 유저가 브라우저 주소창에 ~/catalog-service/~를 입력하면 service를 보고 id를 확인하고 uri로 넘어간다.
        - Method=GET, POST, PUT, DELETE # 해당 코드를 아예 적지 않으면 모두 허용이다.   
 
      - id: reply-service #순서 2
        uri: lb://REPLY-SERVICE #순서3
        predicates:
        - Path=/reply-service/** # 순서1 / 유저가 브라우저 주소창에 ~/order-service/~를 입력하면  order-service를 보고 id를 확인하고 uri로 넘어간다.
        - Method=GET, POST, PUT, DELETE # 해당 코드를 아예 적지 않으면 모두 허용이다.  
 
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # 유레카 서버에 등록
    fetch-registry: true # 주기적으로 다른 인스턴스의 데이터를 받아와 갱싱
    service-url:
      defaultZone: http://localhost:8888/eureka # 유레카 커서의 주소 정보 